Python 3.8.10 (default, Jun  2 2021, 10:49:15) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license()" for more information.
>>> 
=================================== RESTART: /home/katya/learning/Case_18.py ===================================
Enter: 234
Traceback (most recent call last):
  File "/usr/lib/python3.8/idlelib/run.py", line 559, in runcode
    exec(code, self.locals)
  File "/home/katya/learning/Case_18.py", line 106, in <module>
    if n_2 != ' ':
NameError: name 'n_2' is not defined
>>> 
=================================== RESTART: /home/katya/learning/Case_18.py ===================================
Enter: 234
Traceback (most recent call last):
  File "/usr/lib/python3.8/idlelib/run.py", line 559, in runcode
    exec(code, self.locals)
  File "/home/katya/learning/Case_18.py", line 118, in <module>
    print (n_1,n_3,n_4_)
NameError: name 'n_4_' is not defined
>>> 
=================================== RESTART: /home/katya/learning/Case_18.py ===================================
Enter: 234
Traceback (most recent call last):
  File "/usr/lib/python3.8/idlelib/run.py", line 559, in runcode
    exec(code, self.locals)
  File "/home/katya/learning/Case_18.py", line 118, in <module>
    print (n_1,n_3,n_4)
NameError: name 'n_4' is not defined
>>> 
=================================== RESTART: /home/katya/learning/Case_18.py ===================================
Enter: 211
двести одиннадцать
Enter: 
Traceback (most recent call last):
  File "/usr/lib/python3.8/idlelib/run.py", line 559, in runcode
    exec(code, self.locals)
  File "/home/katya/learning/Case_18.py", line 2, in <module>
    num = int(input('Enter: '))
  File "/usr/lib/python3.8/idlelib/run.py", line 484, in readline
    line = self._line_buffer or self.shell.readline()
  File "/usr/lib/python3.8/idlelib/rpc.py", line 607, in __call__
    value = self.sockio.remotecall(self.oid, self.name, args, kwargs)
  File "/usr/lib/python3.8/idlelib/rpc.py", line 219, in remotecall
    return self.asyncreturn(seq)
  File "/usr/lib/python3.8/idlelib/rpc.py", line 248, in asyncreturn
    response = self.getresponse(seq, wait=0.05)
  File "/usr/lib/python3.8/idlelib/rpc.py", line 291, in getresponse
    response = self._getresponse(myseq, wait)
  File "/usr/lib/python3.8/idlelib/rpc.py", line 319, in _getresponse
    cvar.wait()
  File "/usr/lib/python3.8/threading.py", line 302, in wait
    waiter.acquire()
KeyboardInterrupt
>>> 
=================================== RESTART: /home/katya/learning/Case_18.py ===================================
Enter: 201
двести   один
Enter: 401
четыресто   один
Enter: 222
двести двадцать один
Enter: 223
двести двадцать один
Enter: 
=================================== RESTART: /home/katya/learning/Case_18.py ===================================
Enter: 201
двести   один
Enter: 222
двести двадцать два
Enter: 234
двести тридцать четыре
Enter: 211
двести одиннадцать
Enter: 504
пятьсот   четыре
Enter: 544
пятьсот сорок четыре
Enter: 999
девятьсот девяносто девять
Enter: 345
триста сорок пять
Enter: 
Traceback (most recent call last):
  File "/usr/lib/python3.8/idlelib/run.py", line 559, in runcode
    exec(code, self.locals)
  File "/home/katya/learning/Case_18.py", line 2, in <module>
    num = int(input('Enter: '))
  File "/usr/lib/python3.8/idlelib/run.py", line 484, in readline
    line = self._line_buffer or self.shell.readline()
  File "/usr/lib/python3.8/idlelib/rpc.py", line 607, in __call__
    value = self.sockio.remotecall(self.oid, self.name, args, kwargs)
  File "/usr/lib/python3.8/idlelib/rpc.py", line 219, in remotecall
    return self.asyncreturn(seq)
  File "/usr/lib/python3.8/idlelib/rpc.py", line 248, in asyncreturn
    response = self.getresponse(seq, wait=0.05)
  File "/usr/lib/python3.8/idlelib/rpc.py", line 291, in getresponse
    response = self._getresponse(myseq, wait)
  File "/usr/lib/python3.8/idlelib/rpc.py", line 319, in _getresponse
    cvar.wait()
  File "/usr/lib/python3.8/threading.py", line 302, in wait
    waiter.acquire()
KeyboardInterrupt
>>> 
=================================== RESTART: /home/katya/learning/Case_20.py ===================================
Enter day: 2
Enter month: 12
Стрелец
Enter day: 1
Enter month: 1
Козерог
Enter day: 4
Enter month: 1
Козерог
Enter day: 11
Enter month: 4
Овен
Enter day: 11
Enter month: 3
Рыбы
Enter day: 
Traceback (most recent call last):
  File "/usr/lib/python3.8/idlelib/run.py", line 559, in runcode
    exec(code, self.locals)
  File "/home/katya/learning/Case_20.py", line 2, in <module>
    d = int(input('Enter day: '))
  File "/usr/lib/python3.8/idlelib/run.py", line 484, in readline
    line = self._line_buffer or self.shell.readline()
  File "/usr/lib/python3.8/idlelib/rpc.py", line 607, in __call__
    value = self.sockio.remotecall(self.oid, self.name, args, kwargs)
  File "/usr/lib/python3.8/idlelib/rpc.py", line 219, in remotecall
    return self.asyncreturn(seq)
  File "/usr/lib/python3.8/idlelib/rpc.py", line 248, in asyncreturn
    response = self.getresponse(seq, wait=0.05)
  File "/usr/lib/python3.8/idlelib/rpc.py", line 291, in getresponse
    response = self._getresponse(myseq, wait)
  File "/usr/lib/python3.8/idlelib/rpc.py", line 319, in _getresponse
    cvar.wait()
  File "/usr/lib/python3.8/threading.py", line 302, in wait
    waiter.acquire()
KeyboardInterrupt
>>> 
==================================== RESTART: /home/katya/learning/For_1.py ====================================
Enter num 3
Enter num_ch2
3.0
3.0
Enter num
==================================== RESTART: /home/katya/learning/For_1.py ====================================
Enter num: 3
Enter num_ch: 24
3.0
3.0
3.0
3.0
3.0
3.0
3.0
3.0
3.0
3.0
3.0
3.0
3.0
3.0
3.0
3.0
3.0
3.0
3.0
3.0
3.0
3.0
3.0
3.0
Enter num: 
==================================== RESTART: /home/katya/learning/For_2.py ====================================
A: 4
B: 7
4
5
3
A: 
==================================== RESTART: /home/katya/learning/For_2.py ====================================
A: 2
B: 5
2
3
4
3
A: 
==================================== RESTART: /home/katya/learning/For_2.py ====================================
A: 2
B: 5
2
3
4
5
3
A: 
==================================== RESTART: /home/katya/learning/For_2.py ====================================
A: 3
B: 6
3
4
5
6
Общее число: 5
A: 
==================================== RESTART: /home/katya/learning/For_2.py ====================================
A: 3
B: 6
3
4
5
6
Общее число: 4
A: 
Traceback (most recent call last):
  File "/usr/lib/python3.8/idlelib/run.py", line 559, in runcode
    exec(code, self.locals)
  File "/home/katya/learning/For_2.py", line 2, in <module>
    A = int(input('A: '))
  File "/usr/lib/python3.8/idlelib/run.py", line 484, in readline
    line = self._line_buffer or self.shell.readline()
  File "/usr/lib/python3.8/idlelib/rpc.py", line 607, in __call__
    value = self.sockio.remotecall(self.oid, self.name, args, kwargs)
  File "/usr/lib/python3.8/idlelib/rpc.py", line 219, in remotecall
    return self.asyncreturn(seq)
  File "/usr/lib/python3.8/idlelib/rpc.py", line 248, in asyncreturn
    response = self.getresponse(seq, wait=0.05)
  File "/usr/lib/python3.8/idlelib/rpc.py", line 291, in getresponse
    response = self._getresponse(myseq, wait)
  File "/usr/lib/python3.8/idlelib/rpc.py", line 319, in _getresponse
    cvar.wait()
  File "/usr/lib/python3.8/threading.py", line 302, in wait
    waiter.acquire()
KeyboardInterrupt
>>> 
==================================== RESTART: /home/katya/learning/For_2.py ====================================
A: 4
B: 6
Общее число: 3
6
A: 
==================================== RESTART: /home/katya/learning/For_2.py ====================================
A: 3
B: 5
Traceback (most recent call last):
  File "/usr/lib/python3.8/idlelib/run.py", line 559, in runcode
    exec(code, self.locals)
  File "/home/katya/learning/For_2.py", line 15, in <module>
    k[1][:] = A+i
IndexError: list index out of range
>>> 
==================================== RESTART: /home/katya/learning/For_2.py ====================================
A: 3
B: 5
Traceback (most recent call last):
  File "/usr/lib/python3.8/idlelib/run.py", line 559, in runcode
    exec(code, self.locals)
  File "/home/katya/learning/For_2.py", line 15, in <module>
    k[1][i] = A+i
IndexError: list index out of range
>>> 
==================================== RESTART: /home/katya/learning/For_2.py ====================================
A: 4
B: 6
Traceback (most recent call last):
  File "/usr/lib/python3.8/idlelib/run.py", line 559, in runcode
    exec(code, self.locals)
  File "/home/katya/learning/For_2.py", line 16, in <module>
    k[1][i] = A+i
IndexError: list index out of range
>>> 
==================================== RESTART: /home/katya/learning/For_2.py ====================================
A: 4
B: 6
Общее число: 3
[4, 5, 6, 7]
A: 
==================================== RESTART: /home/katya/learning/For_2.py ====================================
A: 3
B: 5
Общее число: 3
[3, 4, 5]
A: 
==================================== RESTART: /home/katya/learning/For_3.py ====================================
A: 4
B: 8
Общее число: 5
[8, 7, 6, 5, 4]
A: 
==================================== RESTART: /home/katya/learning/For_3.py ====================================
A: 4
B: 8
Общее число: 5
[8, 7, 6, 5]
A: 
==================================== RESTART: /home/katya/learning/For_3.py ====================================
A: 3
B: 8
Общее число: 4
[8, 7, 6, 5, 4]
A: 
==================================== RESTART: /home/katya/learning/For_3.py ====================================
A: 4
B: 9
Общее число: 4
[8, 7, 6, 5, 4]
A: 
==================================== RESTART: /home/katya/learning/For_3.py ====================================
A: 4
B: 9
Общее число: 4
[8, 7, 6, 5]
A: 
==================================== RESTART: /home/katya/learning/For_3.py ====================================
A: 5
B: 8
Общее число: 2
[8, 7, 6]
A: 
==================================== RESTART: /home/katya/learning/For_3.py ====================================
A: 6
B: 9
Общее число: 2
[9, 8, 7]
A: 
==================================== RESTART: /home/katya/learning/For_3.py ====================================
A: 6
B: 9
Общее число: 2
[8, 7, 6]
A: 
==================================== RESTART: /home/katya/learning/For_3.py ====================================
A: 6
B: 9
Общее число: 3
[8, 7, 6]
A: 
==================================== RESTART: /home/katya/learning/For_2.py ====================================
A: 5
B: 9
Общее число: 5
[5, 6, 7, 8, 9]
A: 
==================================== RESTART: /home/katya/learning/For_4.py ====================================
Стоимость кг: 56
Стоимость 0 кг:  0.0
Стоимость 1 кг:  56.0
Стоимость 2 кг:  112.0
Стоимость 3 кг:  168.0
Стоимость 4 кг:  224.0
Стоимость 5 кг:  280.0
Стоимость 6 кг:  336.0
Стоимость 7 кг:  392.0
Стоимость 8 кг:  448.0
Стоимость 9 кг:  504.0
Стоимость кг: 
==================================== RESTART: /home/katya/learning/For_4.py ====================================
Стоимость кг: 56
Стоимость 0 кг:  0.0
Стоимость 1 кг:  56.0
Стоимость 2 кг:  112.0
Стоимость 3 кг:  168.0
Стоимость 4 кг:  224.0
Стоимость 5 кг:  280.0
Стоимость 6 кг:  336.0
Стоимость 7 кг:  392.0
Стоимость 8 кг:  448.0
Стоимость 9 кг:  504.0
Стоимость кг: 
==================================== RESTART: /home/katya/learning/For_4.py ====================================
Стоимость кг: 45
Стоимость 1 кг:  45.0
Стоимость 2 кг:  90.0
Стоимость 3 кг:  135.0
Стоимость 4 кг:  180.0
Стоимость 5 кг:  225.0
Стоимость 6 кг:  270.0
Стоимость 7 кг:  315.0
Стоимость 8 кг:  360.0
Стоимость 9 кг:  405.0
Стоимость кг: 
==================================== RESTART: /home/katya/learning/For_4.py ====================================
Стоимость кг: 34
Стоимость 1 кг:  34.0
Стоимость 2 кг:  68.0
Стоимость 3 кг:  102.0
Стоимость 4 кг:  136.0
Стоимость 5 кг:  170.0
Стоимость 6 кг:  204.0
Стоимость 7 кг:  238.0
Стоимость 8 кг:  272.0
Стоимость 9 кг:  306.0
Стоимость 10 кг:  340.0
Стоимость кг: 
==================================== RESTART: /home/katya/learning/For_2.py ====================================
A: 
==================================== RESTART: /home/katya/learning/For_2.py ====================================
A: 4
B: 7
Общее число: 4
[4, 5, 6, 7]
A: 
==================================== RESTART: /home/katya/learning/For_3.py ====================================
A: 4
B: 7
Общее число: 3
[5, 4]
A: 
==================================== RESTART: /home/katya/learning/For_3.py ====================================
A: 5
B: 8
Общее число: 2
[7, 6, 5]
A: 
==================================== RESTART: /home/katya/learning/For_3.py ====================================
A: 5
B: 
Traceback (most recent call last):
  File "/usr/lib/python3.8/idlelib/run.py", line 559, in runcode
    exec(code, self.locals)
  File "/home/katya/learning/For_3.py", line 3, in <module>
    B = int(input('B: '))
ValueError: invalid literal for int() with base 10: ''
>>> 
==================================== RESTART: /home/katya/learning/For_3.py ====================================
A: 
4
B: 5
Общее число: 0
[]
A: 5
B: 8
Общее число: 2
[7, 6]
A: 
==================================== RESTART: /home/katya/learning/For_5.py ====================================
Enter: 56
Traceback (most recent call last):
  File "/usr/lib/python3.8/idlelib/run.py", line 559, in runcode
    exec(code, self.locals)
  File "/home/katya/learning/For_5.py", line 5, in <module>
    for i in range (0.1, 0.1, 1):
TypeError: 'float' object cannot be interpreted as an integer
>>> 
==================================== RESTART: /home/katya/learning/For_5.py ====================================
Enter: 5
Traceback (most recent call last):
  File "/usr/lib/python3.8/idlelib/run.py", line 559, in runcode
    exec(code, self.locals)
  File "/home/katya/learning/For_5.py", line 5, in <module>
    for i in range (0.1, 0.1, 1):
TypeError: 'float' object cannot be interpreted as an integer
>>> 
==================================== RESTART: /home/katya/learning/For_5.py ====================================
Enter: 5
Traceback (most recent call last):
  File "/usr/lib/python3.8/idlelib/run.py", line 559, in runcode
    exec(code, self.locals)
  File "/home/katya/learning/For_5.py", line 5, in <module>
    for i in range (0.1, 0.1, 1):
TypeError: 'float' object cannot be interpreted as an integer
>>> 
==================================== RESTART: /home/katya/learning/For_5.py ====================================
Enter: 5
Traceback (most recent call last):
  File "/usr/lib/python3.8/idlelib/run.py", line 559, in runcode
    exec(code, self.locals)
  File "/home/katya/learning/For_5.py", line 5, in <module>
    for i in range (0,1, 0,1, 1):
TypeError: range expected at most 3 arguments, got 5
>>> 
==================================== RESTART: /home/katya/learning/For_5.py ====================================
Enter: 5
Traceback (most recent call last):
  File "/usr/lib/python3.8/idlelib/run.py", line 559, in runcode
    exec(code, self.locals)
  File "/home/katya/learning/For_5.py", line 5, in <module>
    for i in range (0.1, 1):
TypeError: 'float' object cannot be interpreted as an integer
>>> 
==================================== RESTART: /home/katya/learning/For_5.py ====================================
Enter: 5
Traceback (most recent call last):
  File "/usr/lib/python3.8/idlelib/run.py", line 559, in runcode
    exec(code, self.locals)
  File "/home/katya/learning/For_5.py", line 5, in <module>
    for i in range (0.1, 1, 0.1):
TypeError: 'float' object cannot be interpreted as an integer
>>> 
==================================== RESTART: /home/katya/learning/For_5.py ====================================
Enter: 4
0.4
0.8
1.2000000000000002
1.6
2.0
2.4
2.8000000000000003
3.2
3.6
>>> 
==================================== RESTART: /home/katya/learning/For_5.py ====================================
Enter: 1
0.1
0.2
0.30000000000000004
0.4
0.5
0.6
0.7000000000000001
0.8
0.9
1.0
>>> 
==================================== RESTART: /home/katya/learning/For_5.py ====================================
Enter: 2.3
0.22999999999999998
0.45999999999999996
0.6900000000000001
0.9199999999999999
1.15
1.38
1.61
1.8399999999999999
2.07
2.3
>>> 
==================================== RESTART: /home/katya/learning/For_6.py ====================================
Enter: 56
67.2
78.39999999999999
89.6
100.79999999999998
111.99999999999999
123.19999999999999
>>> 
==================================== RESTART: /home/katya/learning/For_7.py ====================================
A: 5
B: 6
10
A: 
==================================== RESTART: /home/katya/learning/For_7.py ====================================
A: 4
B: 5
Traceback (most recent call last):
  File "/usr/lib/python3.8/idlelib/run.py", line 559, in runcode
    exec(code, self.locals)
  File "/home/katya/learning/For_7.py", line 8, in <module>
    print (k)
NameError: name 'k' is not defined
>>> 
==================================== RESTART: /home/katya/learning/For_7.py ====================================
A: 5
B: 6
10
A: 7
B: 11
17
A: 
==================================== RESTART: /home/katya/learning/For_7.py ====================================
A: 4
B: 8
26
A: 
==================================== RESTART: /home/katya/learning/For_7.py ====================================
A: 4
B: 8
22
A: 
==================================== RESTART: /home/katya/learning/For_7.py ====================================
A: 4
B: 8
30
A: 
==================================== RESTART: /home/katya/learning/For_8.py ====================================
A: 5
B: 7
210
A: 
==================================== RESTART: /home/katya/learning/For_9.py ====================================
A: 4
B: 8
178
A: 
==================================== RESTART: /home/katya/learning/For_9.py ====================================
A: 4
B: 8
190
A: 
==================================== RESTART: /home/katya/learning/For_10.py ===================================
Enter: 4
Traceback (most recent call last):
  File "/usr/lib/python3.8/idlelib/run.py", line 559, in runcode
    exec(code, self.locals)
  File "/home/katya/learning/For_10.py", line 6, in <module>
    k = k + 1/N
NameError: name 'k' is not defined
>>> 
==================================== RESTART: /home/katya/learning/For_10.py ===================================
Enter: 5
1.7999999999999998
Enter: 
==================================== RESTART: /home/katya/learning/For_10.py ===================================
Enter: 5
0.8
Enter: 
==================================== RESTART: /home/katya/learning/For_10.py ===================================
Enter: 5
1.2
Enter: 
==================================== RESTART: /home/katya/learning/For_10.py ===================================
Enter: 4
0.25
0.25
0.25
0.25
0.25
Enter: 
==================================== RESTART: /home/katya/learning/For_10.py ===================================
Enter: 5
1.0
0.5
0.3333333333333333
0.25
0.2
0.2
Enter: 
==================================== RESTART: /home/katya/learning/For_10.py ===================================
Enter: 4
1.0
0.5
0.3333333333333333
0.3333333333333333
Enter: 
==================================== RESTART: /home/katya/learning/For_10.py ===================================
Enter: 4
1.0
0.5
0.3333333333333333
1.8333333333333333
Enter: 
==================================== RESTART: /home/katya/learning/For_10.py ===================================
Enter: 4
1.0
0.5
0.3333333333333333
0.25
2.083333333333333
Enter: 
==================================== RESTART: /home/katya/learning/For_11.py ===================================
Enter: 4
25
36
49
64
81
100
121
144
636
Enter: 
==================================== RESTART: /home/katya/learning/For_11.py ===================================
Enter: 4
25
36
49
64
81
100
121
144
636
Enter: 
==================================== RESTART: /home/katya/learning/For_11.py ===================================
Enter: 4
Traceback (most recent call last):
  File "/usr/lib/python3.8/idlelib/run.py", line 559, in runcode
    exec(code, self.locals)
  File "/home/katya/learning/For_11.py", line 5, in <module>
    for i in np.range(1,2*N+1,1):
  File "/home/katya/.local/lib/python3.8/site-packages/numpy/__init__.py", line 214, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'range'
>>> 
==================================== RESTART: /home/katya/learning/For_11.py ===================================
Enter: 4
25
36
49
64
81
100
121
144
636
>>> 
==================================== RESTART: /home/katya/learning/For_11.py ===================================
Enter: 4
25
36
49
64
81
100
121
492
>>> 
==================================== RESTART: /home/katya/learning/For_11.py ===================================
Enter: 5
36
49
64
81
255
>>> 
==================================== RESTART: /home/katya/learning/For_11.py ===================================
Enter: 4
25
36
49
64
190
>>> 
==================================== RESTART: /home/katya/learning/For_12.py ===================================
Enter: 2
1.0
1.1
1.2000000000000002
1.3000000000000003
1.4000000000000004
1.5000000000000004
1.6000000000000005
1.7000000000000006
1.8000000000000007
1.9000000000000008
2.000000000000001
2.100000000000001
2.200000000000001
2.300000000000001
2.4000000000000012
2.5000000000000013
2.6000000000000014
2.7000000000000015
2.8000000000000016
2.9000000000000017
243655.25776399276
>>> 
==================================== RESTART: /home/katya/learning/For_12.py ===================================
Enter: 2
1.1
1
>>> 
==================================== RESTART: /home/katya/learning/For_12.py ===================================
Enter: 2
1.1
1.2
2
>>> 
==================================== RESTART: /home/katya/learning/For_12.py ===================================
Enter: 2
1.1
1.2
1.32
>>> 
==================================== RESTART: /home/katya/learning/For_13.py ===================================
Enter: 4
1.1
1.2
1.3
1.4
1.1999999999999997
>>> 
==================================== RESTART: /home/katya/learning/For_13.py ===================================
Enter: 4
-1.1
1.2
-1.3
1.4
1.1999999999999997
>>> 
==================================== RESTART: /home/katya/learning/For_13.py ===================================
Enter: 4
1.1
-1.2
1.3
-1.4
-0.19999999999999973
>>> 
==================================== RESTART: /home/katya/learning/For_14.py ===================================
Enter: 4
1
3
5
7
16
>>> 
==================================== RESTART: /home/katya/learning/For_14.py ===================================
Enter: 25
1
3
5
7
9
11
13
15
17
19
21
23
25
27
29
31
33
35
37
39
41
43
45
47
49
Квадрат введеного числа:  625
>>> 
==================================== RESTART: /home/katya/learning/For_15.py ===================================
Enter N: 3
Enter A: 3
1
Enter N: 
==================================== RESTART: /home/katya/learning/For_15.py ===================================
Enter N: 3
Enter A: 3
1
1
1
1
Enter N: 
==================================== RESTART: /home/katya/learning/For_15.py ===================================
Enter N: 3
Enter A: 3
Traceback (most recent call last):
  File "/usr/lib/python3.8/idlelib/run.py", line 559, in runcode
    exec(code, self.locals)
  File "/home/katya/learning/For_15.py", line 6, in <module>
    mltp = A*mltpl
NameError: name 'mltpl' is not defined
>>> 
==================================== RESTART: /home/katya/learning/For_15.py ===================================
Enter N: 2
Enter A: 3
1 3
1 3
Enter N: 
==================================== RESTART: /home/katya/learning/For_15.py ===================================
Enter N: 3
Enter A: 3
1 3
1 3
1 3
Enter N: 
==================================== RESTART: /home/katya/learning/For_15.py ===================================
Enter N: 3
Enter A: 4
1 4
1 4
1 4
Enter N: 
==================================== RESTART: /home/katya/learning/For_15.py ===================================
Enter N: 3
Enter A: 3
1 9
1 81
1 6561
1 43046721
Enter N: 
==================================== RESTART: /home/katya/learning/For_15.py ===================================
Enter N: 2
Enter A: 3
1 9
1 81
Enter N: 
==================================== RESTART: /home/katya/learning/For_15.py ===================================
Enter N: 2
Enter A: 3
9
Enter N: 45
Enter A: 1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
Enter N: 
==================================== RESTART: /home/katya/learning/For_15.py ===================================
Enter N: 2
Enter A: 5
25
Enter N: 4
Enter A: 2
256
Enter N: 
==================================== RESTART: /home/katya/learning/For_15.py ===================================
Enter N: 3
Enter A: 2
8
Enter N: 4
Enter A: 2
16
Enter N: 
Traceback (most recent call last):
  File "/usr/lib/python3.8/idlelib/run.py", line 559, in runcode
    exec(code, self.locals)
  File "/home/katya/learning/For_15.py", line 2, in <module>
    N = int(input('Enter N: '))
  File "/usr/lib/python3.8/idlelib/run.py", line 484, in readline
    line = self._line_buffer or self.shell.readline()
  File "/usr/lib/python3.8/idlelib/rpc.py", line 607, in __call__
    value = self.sockio.remotecall(self.oid, self.name, args, kwargs)
  File "/usr/lib/python3.8/idlelib/rpc.py", line 219, in remotecall
    return self.asyncreturn(seq)
  File "/usr/lib/python3.8/idlelib/rpc.py", line 248, in asyncreturn
    response = self.getresponse(seq, wait=0.05)
  File "/usr/lib/python3.8/idlelib/rpc.py", line 291, in getresponse
    response = self._getresponse(myseq, wait)
  File "/usr/lib/python3.8/idlelib/rpc.py", line 319, in _getresponse
    cvar.wait()
  File "/usr/lib/python3.8/threading.py", line 302, in wait
    waiter.acquire()
KeyboardInterrupt
>>> 
==================================== RESTART: /home/katya/learning/For_16.py ===================================
Enter N: 4
Enter A: 3
Traceback (most recent call last):
  File "/usr/lib/python3.8/idlelib/run.py", line 559, in runcode
    exec(code, self.locals)
  File "/home/katya/learning/For_16.py", line 8, in <module>
    sum = sum + F
TypeError: unsupported operand type(s) for +: 'builtin_function_or_method' and 'int'
>>> 
==================================== RESTART: /home/katya/learning/For_16.py ===================================
Enter N: 3
Enter A: 2
4
Enter N: 
==================================== RESTART: /home/katya/learning/For_17.py ===================================
Enter N: 4
Enter A: 2
1
-2
4
-8
-8
Enter N: 8
Enter A: 3
1
-3
9
-27
81
-243
729
-2187
-2187
Enter N: 
==================================== RESTART: /home/katya/learning/For_17.py ===================================
Enter N: 8
Enter A: 3
1
-3
9
-27
81
-243
729
-2187
-2187
Enter N: 
==================================== RESTART: /home/katya/learning/For_17.py ===================================
Enter N: 8
Enter A: 3
1
-3
9
-27
81
-243
729
-2187
-1640
Enter N: 4
Enter A: 2
1
-2
4
-8
-5
Enter N: 
Traceback (most recent call last):
  File "/usr/lib/python3.8/idlelib/run.py", line 559, in runcode
    exec(code, self.locals)
  File "/home/katya/learning/For_17.py", line 2, in <module>
    N = int(input('Enter N: '))
  File "/usr/lib/python3.8/idlelib/run.py", line 484, in readline
    line = self._line_buffer or self.shell.readline()
  File "/usr/lib/python3.8/idlelib/rpc.py", line 607, in __call__
    value = self.sockio.remotecall(self.oid, self.name, args, kwargs)
  File "/usr/lib/python3.8/idlelib/rpc.py", line 219, in remotecall
    return self.asyncreturn(seq)
  File "/usr/lib/python3.8/idlelib/rpc.py", line 248, in asyncreturn
    response = self.getresponse(seq, wait=0.05)
  File "/usr/lib/python3.8/idlelib/rpc.py", line 291, in getresponse
    response = self._getresponse(myseq, wait)
  File "/usr/lib/python3.8/idlelib/rpc.py", line 319, in _getresponse
    cvar.wait()
  File "/usr/lib/python3.8/threading.py", line 302, in wait
    waiter.acquire()
KeyboardInterrupt
>>> 